<?php

use App\Enums\OrganizationRole;
use App\Models\Organization;
use App\Models\User;

test('seeding produces the three organizations owned by the test user', function () {
    $this->seed();

    $owner = User::where('email', 'test@example.com')->firstOrFail();

    expect(Organization::count())->toBe(3);

    Organization::each(function (Organization $organization) use ($owner) {
        expect($owner->ownsOrganization($organization))->toBeTrue();
    });
});

test('seeded slugs are generated by the model, not hand written', function () {
    $this->seed();

    expect(Organization::pluck('slug')->sort()->values()->all())
        ->toBe(['92-labs', 'notarydash', 'vheissulabs']);
});

test('every seeded organization has members and a client contact', function () {
    $this->seed();

    expect(Organization::count())->toBe(3);

    Organization::each(function (Organization $organization) {
        $roles = $organization->memberships->pluck('role');

        expect($roles)->toContain(OrganizationRole::Owner);
        expect($roles)->toContain(OrganizationRole::Client);
        expect($roles->filter(fn (OrganizationRole $role) => $role === OrganizationRole::Member))
            ->toHaveCount(2);
    });
});

test('every seeded key is a uuid', function () {
    $this->seed();

    expect(Organization::count())->toBe(3);

    Organization::each(function (Organization $organization) {
        expect(Str::isUuid($organization->id))->toBeTrue();

        $organization->memberships->each(
            fn ($membership) => expect(Str::isUuid($membership->id))->toBeTrue(),
        );
    });
});
