<?php

use App\Enums\OrganizationRole;
use App\Models\Organization;
use App\Models\User;

test('seeding produces the three organizations', function () {
    $this->seed();

    expect(Organization::count())->toBe(3);
});

test('each organization is owned by the person who actually owns it', function () {
    $this->seed();

    $owners = [
        'NotaryDash' => 'jen@notarydash.com',
        '92 Labs' => 'jerry@92labs.com',
        'VheissuLabs' => 'karl@vheissulabs.com',
    ];

    foreach ($owners as $organizationName => $email) {
        $organization = Organization::where('name', $organizationName)->firstOrFail();
        $owner = User::where('email', $email)->firstOrFail();

        expect($owner->ownsOrganization($organization))->toBeTrue();
    }
});

test('the test user holds a different role in each organization', function () {
    $this->seed();

    $user = User::where('email', 'karl@vheissulabs.com')->firstOrFail();

    $expected = [
        'NotaryDash' => OrganizationRole::Admin,
        '92 Labs' => OrganizationRole::Member,
        'VheissuLabs' => OrganizationRole::Owner,
    ];

    foreach ($expected as $organizationName => $role) {
        $organization = Organization::where('name', $organizationName)->firstOrFail();

        expect($user->organizationRole($organization))->toBe($role);
    }
});

test('the test user belongs to exactly the three organizations', function () {
    $this->seed();

    $user = User::where('email', 'karl@vheissulabs.com')->firstOrFail();

    expect($user->organizations()->count())->toBe(3);
});

test('the test user starts in NotaryDash', function () {
    $this->seed();

    $user = User::where('email', 'karl@vheissulabs.com')->firstOrFail();

    expect($user->currentOrganization->name)->toBe('NotaryDash');
});

test('seeded slugs are generated by the model, not hand written', function () {
    $this->seed();

    expect(Organization::pluck('slug')->sort()->values()->all())
        ->toBe(['92-labs', 'notarydash', 'vheissulabs']);
});

test('every seeded organization has members and a client contact', function () {
    $this->seed();

    expect(Organization::count())->toBe(3);

    Organization::each(function (Organization $organization) {
        $roles = $organization->memberships->pluck('role');

        expect($roles)->toContain(OrganizationRole::Owner);
        expect($roles)->toContain(OrganizationRole::Client);
        expect($roles->filter(fn (OrganizationRole $role) => $role === OrganizationRole::Member)->count())
            ->toBeGreaterThanOrEqual(2);
    });
});

test('every seeded key is a uuid', function () {
    $this->seed();

    expect(Organization::count())->toBe(3);

    Organization::each(function (Organization $organization) {
        expect(Str::isUuid($organization->id))->toBeTrue();

        $organization->memberships->each(
            fn ($membership) => expect(Str::isUuid($membership->id))->toBeTrue(),
        );
    });
});
